package com.fynal.item;

import java.awt.List;

import com.fynal.Main.MainRegistry;
import com.fynal.lib.Ref;

import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.relauncher.ReflectionHelper;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.item.Item;
import net.minecraft.item.Item.ToolMaterial;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.util.EnumHelper;

public class ModTools {
	
										   /*  VANILLA VALUES(DURABILITY, ARMOR PER ITEM, ENCHANTABILITY)
						 					*  CLOTH(5, new int[]{1, 3, 2, 1}, 15),
						 					*  CHAIN(15, new int[]{2, 5, 4, 1}, 12),
						 					*  IRON(15, new int[]{2, 6, 5, 2}, 9),
						 					*  GOLD(7, new int[]{2, 5, 3, 1}, 25),
						 					*  DIAMOND(33, new int[]{3, 8, 6, 3}, 10);
						 					*  
						 					*Coilcraft tiers approximately: {1, 3, 2, 1}(L,C,I)  {2, 5, 3, 1}(brass/lowbronze)  {3, 6, 5, 2}(highbronze/lowsteel)  {3, 8, 6, 3}(highsteel)
						 					*/
	public static ArmorMaterial rose_gold_armor_material = EnumHelper.addArmorMaterial("rose_gold_armor_material", 11, new int[]{2, 5, 3, 1}, 10);

	public static ArmorMaterial copper_armor_material = EnumHelper.addArmorMaterial("copper_armor_material", 10, new int[]{1, 3, 2, 1}, 10);
	public static ArmorMaterial iron_armor_material = EnumHelper.addArmorMaterial("iron_armor_material", 13, new int[]{1, 4, 2, 1}, 8);
	public static ArmorMaterial brass_z_armor_material = EnumHelper.addArmorMaterial("brass_z_armor_material", 13, new int[]{2, 5, 3, 1}, 10);
	public static ArmorMaterial brass_zz_armor_material = EnumHelper.addArmorMaterial("brass_zz_armor_material", 16, new int[]{2, 5, 3, 1}, 10);
	public static ArmorMaterial bronze_t_armor_material = EnumHelper.addArmorMaterial("bronze_t_armor_material", 11, new int[]{2, 5, 4, 1}, 10);
	public static ArmorMaterial bronze_tt_armor_material = EnumHelper.addArmorMaterial("bronze_tt_armor_material", 12, new int[]{3, 6, 5, 2}, 10);
	public static ArmorMaterial bronze_tz_armor_material = EnumHelper.addArmorMaterial("bronze_tz_armor_material", 15, new int[]{2, 6, 5, 2}, 10);
	
	public static ArmorMaterial steel_c_armor_material = EnumHelper.addArmorMaterial("steel_c_armor_material", 10, new int[]{3, 6, 5, 2}, 10);
	public static ArmorMaterial steel_cc_armor_material = EnumHelper.addArmorMaterial("steel_cc_armor_material", 7, new int[]{3, 8, 6, 3}, 10);
	public static ArmorMaterial steel_n_armor_material = EnumHelper.addArmorMaterial("steel_n_armor_material", 20, new int[]{3, 6, 5, 2}, 10);
	public static ArmorMaterial steel_nn_armor_material = EnumHelper.addArmorMaterial("steel_nn_armor_material", 32, new int[]{3, 6, 5, 2}, 10);
	public static ArmorMaterial steel_b_armor_material = EnumHelper.addArmorMaterial("steel_b_armor_material", 33, new int[]{3, 6, 5, 2}, 10);
	public static ArmorMaterial steel_bb_armor_material = EnumHelper.addArmorMaterial("steel_bb_armor_material", 53, new int[]{3, 6, 5, 2}, 10);
	public static ArmorMaterial steel_t_armor_material = EnumHelper.addArmorMaterial("steel_t_armor_material", 16, new int[]{3, 7, 5, 3}, 10);
	public static ArmorMaterial steel_tt_armor_material = EnumHelper.addArmorMaterial("steel_tt_armor_material", 19, new int[]{3, 8, 6, 3}, 10);

	public static ArmorMaterial steel_cn_armor_material = EnumHelper.addArmorMaterial("steel_cn_armor_material", 17, new int[]{3, 7, 5, 3}, 10);
	public static ArmorMaterial steel_cb_armor_material = EnumHelper.addArmorMaterial("steel_cb_armor_material", 26, new int[]{3, 7, 5, 3}, 10);
	public static ArmorMaterial steel_ct_armor_material = EnumHelper.addArmorMaterial("steel_ct_armor_material", 14, new int[]{3, 8, 6, 3}, 10);
	public static ArmorMaterial steel_nb_armor_material = EnumHelper.addArmorMaterial("steel_nb_armor_material", 42, new int[]{3, 7, 5, 3}, 10);
	public static ArmorMaterial steel_nt_armor_material = EnumHelper.addArmorMaterial("steel_nt_armor_material", 22, new int[]{3, 8, 6, 3}, 10);
	public static ArmorMaterial steel_bt_armor_material = EnumHelper.addArmorMaterial("steel_bt_armor_material", 36, new int[]{3, 8, 6, 3}, 10);

	
	public static final float copper_STR = -1.0f;
	public static final int copper_DUR = 125;
	
	public static final float zinc_STR = 2.0f;
	public static final int zinc_DUR = 175;
	
	public static final float tin_STR = 3.0f;
	public static final int tin_DUR = 75;
	
	public static final float iron_STR = 0.0f;
	public static final int iron_DUR = 250;
	
	public static final float carbon_STR = 5.0f;
	public static final int carbon_DUR = -50;
	
	public static final float nickel_STR = 3.0f;
	public static final int nickel_DUR = 500;
	
	public static final float cobalt_STR = 2.0f;
	public static final int cobalt_DUR = 1500;
	
	public static final float titanium_STR = 8.0f;
	public static final int titanium_DUR = 100;
	
	public static final float brass_z_STR = copper_STR + zinc_STR;
	public static final int brass_z_DUR = copper_DUR + zinc_DUR;
	public static final float brass_zz_STR = copper_STR + zinc_STR + zinc_STR;
	public static final int brass_zz_DUR = copper_DUR + zinc_DUR + zinc_DUR;
	public static final float bronze_t_STR = copper_STR + tin_STR;
	public static final int bronze_t_DUR = copper_DUR + tin_DUR;
	public static final float bronze_tt_STR = copper_STR + tin_STR + tin_STR;
	public static final int bronze_tt_DUR = copper_DUR + tin_DUR + tin_DUR;
	public static final float bronze_tz_STR = copper_STR + tin_STR + zinc_STR;
	public static final int bronze_tz_DUR = copper_DUR + tin_DUR + zinc_DUR;
	
	public static final float steel_c_STR = iron_STR + carbon_STR;
	public static final int steel_c_DUR = iron_DUR + carbon_DUR;
	public static final float steel_cc_STR = iron_STR + carbon_STR + carbon_STR;
	public static final int steel_cc_DUR = iron_DUR + carbon_DUR + carbon_DUR;
	public static final float steel_n_STR = iron_STR + nickel_STR;
	public static final int steel_n_DUR = iron_DUR + nickel_DUR;
	public static final float steel_nn_STR = iron_STR + nickel_STR + nickel_STR;
	public static final int steel_nn_DUR = iron_DUR + nickel_DUR + nickel_DUR;
	public static final float steel_b_STR = iron_STR + cobalt_STR;
	public static final int steel_b_DUR = iron_DUR + cobalt_DUR;
	public static final float steel_bb_STR = iron_STR + cobalt_STR + cobalt_STR;
	public static final int steel_bb_DUR = iron_DUR + cobalt_DUR + cobalt_DUR;
	public static final float steel_t_STR = iron_STR + titanium_STR;
	public static final int steel_t_DUR = iron_DUR + titanium_DUR;
	public static final float steel_tt_STR = iron_STR + titanium_STR + titanium_STR;
	public static final int steel_tt_DUR = iron_DUR + titanium_DUR + titanium_DUR;
	
	public static final float steel_cn_STR = iron_STR + carbon_STR + nickel_STR;
	public static final int steel_cn_DUR = iron_DUR + carbon_DUR + nickel_DUR;
	public static final float steel_cb_STR = iron_STR + carbon_STR + cobalt_STR;
	public static final int steel_cb_DUR = iron_DUR + carbon_DUR + cobalt_DUR;
	public static final float steel_ct_STR = iron_STR + carbon_STR + titanium_STR;
	public static final int steel_ct_DUR = iron_DUR + carbon_DUR + titanium_DUR;
	public static final float steel_nb_STR = iron_STR + nickel_STR + cobalt_STR;
	public static final int steel_nb_DUR = iron_DUR + nickel_DUR + cobalt_DUR;
	public static final float steel_nt_STR = iron_STR + nickel_STR + titanium_STR;
	public static final int steel_nt_DUR = iron_DUR + nickel_DUR + titanium_DUR;
	public static final float steel_bt_STR = iron_STR + cobalt_STR + titanium_STR;
	public static final int steel_bt_DUR = iron_DUR + cobalt_DUR + titanium_DUR;
		
	public static ToolMaterial rose_gold = EnumHelper.addToolMaterial("Rose Gold Ingot", 2, brass_z_DUR, (float) (1.5*brass_z_STR+3.75), brass_z_STR, 10);
	
	public static ToolMaterial copper = EnumHelper.addToolMaterial("Copper Ingot", 1, copper_DUR, (float) (1.5*copper_STR+3.75), copper_STR, 10);
	public static ToolMaterial iron = EnumHelper.addToolMaterial("Iron Ingot", 1, iron_DUR, (float) (1.5*iron_STR+3.75), iron_STR, 10);
	public static ToolMaterial brassz = EnumHelper.addToolMaterial("Brass_z Ingot", 2, brass_z_DUR, (float) (1.5*brass_z_STR+3.75), brass_z_STR, 10);
	public static ToolMaterial brasszz = EnumHelper.addToolMaterial("Brass_z Ingot", 2, brass_zz_DUR, (float) (1.5*brass_zz_STR+3.75), brass_zz_STR, 10);
	public static ToolMaterial bronzet = EnumHelper.addToolMaterial("Brass_z Ingot", 2, bronze_t_DUR, (float) (1.5*bronze_t_STR+3.75), bronze_t_STR, 10);
	public static ToolMaterial bronzett = EnumHelper.addToolMaterial("Brass_z Ingot", 2, bronze_tt_DUR, (float) (1.5*bronze_tt_STR+3.75), bronze_tt_STR, 10);
	public static ToolMaterial bronzetz = EnumHelper.addToolMaterial("Brass_z Ingot", 2, bronze_tz_DUR, (float) (1.5*bronze_tz_STR+3.75), bronze_tz_STR, 10);

	public static ToolMaterial steelc = EnumHelper.addToolMaterial("Steel_c Ingot", 3, steel_c_DUR, (float) (1.5*steel_c_STR+3.75), steel_c_STR, 5);
	public static ToolMaterial steelcc = EnumHelper.addToolMaterial("Steel_cc Ingot", 3, steel_cc_DUR, (float) (1.5*steel_cc_STR+3.75), steel_cc_STR, 5);
	public static ToolMaterial steeln = EnumHelper.addToolMaterial("Steel_n Ingot", 3, steel_n_DUR, (float) (1.5*steel_n_STR+3.75), steel_n_STR, 5);
	public static ToolMaterial steelnn = EnumHelper.addToolMaterial("Steel_nn Ingot", 3, steel_nn_DUR, (float) (1.5*steel_nn_STR+3.75), steel_nn_STR, 5);
	public static ToolMaterial steelb = EnumHelper.addToolMaterial("Steel_b Ingot", 3, steel_b_DUR, (float) (1.5*steel_b_STR+3.75), steel_b_STR, 5);
	public static ToolMaterial steelbb = EnumHelper.addToolMaterial("Steel_bb Ingot", 3, steel_bb_DUR, (float) (1.5*steel_bb_STR+3.75), steel_bb_STR, 5);
	public static ToolMaterial steelt = EnumHelper.addToolMaterial("Steel_t Ingot", 3, steel_t_DUR, (float) (1.5*steel_t_STR+3.75), steel_t_STR, 5);
	public static ToolMaterial steeltt = EnumHelper.addToolMaterial("Steel_tt Ingot", 3, steel_tt_DUR, (float) (1.5*steel_tt_STR+3.75), steel_tt_STR, 5);
	
	public static ToolMaterial steelcn = EnumHelper.addToolMaterial("Steel_cn Ingot", 3, steel_cn_DUR, (float) (1.5*steel_cn_STR+3.75), steel_cn_STR, 5);
	public static ToolMaterial steelcb = EnumHelper.addToolMaterial("Steel_cb Ingot", 3, steel_cb_DUR, (float) (1.5*steel_cb_STR+3.75), steel_cb_STR, 5);
	public static ToolMaterial steelct = EnumHelper.addToolMaterial("Steel_ct Ingot", 3, steel_ct_DUR, (float) (1.5*steel_ct_STR+3.75), steel_ct_STR, 5);
	public static ToolMaterial steelnb = EnumHelper.addToolMaterial("Steel_nb Ingot", 3, steel_nb_DUR, (float) (1.5*steel_nb_STR+3.75), steel_nb_STR, 5);
	public static ToolMaterial steelnt = EnumHelper.addToolMaterial("Steel_nt Ingot", 3, steel_nt_DUR, (float) (1.5*steel_nt_STR+3.75), steel_nt_STR, 5);
	public static ToolMaterial steelbt = EnumHelper.addToolMaterial("Steel_tb Ingot", 3, steel_bt_DUR, (float) (1.5*steel_bt_STR+3.75), steel_bt_STR, 5);
	
	public static Item rose_gold_helmet;
	public static Item rose_gold_chestplate;
	public static Item rose_gold_leggings;
	public static Item rose_gold_boots;
	
	public static Item mod_iron_helmet;
	public static Item mod_iron_chestplate;
	public static Item mod_iron_leggings;
	public static Item mod_iron_boots;
	
	public static Item copper_helmet;
	public static Item copper_chestplate;
	public static Item copper_leggings;
	public static Item copper_boots;
	public static Item brass_z_helmet;
	public static Item brass_z_chestplate;
	public static Item brass_z_leggings;
	public static Item brass_z_boots;
	public static Item brass_zz_helmet;
	public static Item brass_zz_chestplate;
	public static Item brass_zz_leggings;
	public static Item brass_zz_boots;
	public static Item bronze_t_helmet;
	public static Item bronze_t_chestplate;
	public static Item bronze_t_leggings;
	public static Item bronze_t_boots;
	public static Item bronze_tt_helmet;
	public static Item bronze_tt_chestplate;
	public static Item bronze_tt_leggings;
	public static Item bronze_tt_boots;
	public static Item bronze_tz_helmet;
	public static Item bronze_tz_chestplate;
	public static Item bronze_tz_leggings;
	public static Item bronze_tz_boots;
	public static Item steel_c_helmet;
	public static Item steel_c_chestplate;
	public static Item steel_c_leggings;
	public static Item steel_c_boots;
	public static Item steel_cc_helmet;
	public static Item steel_cc_chestplate;
	public static Item steel_cc_leggings;
	public static Item steel_cc_boots;
	public static Item steel_n_helmet;
	public static Item steel_n_chestplate;
	public static Item steel_n_leggings;
	public static Item steel_n_boots;
	public static Item steel_nn_helmet;
	public static Item steel_nn_chestplate;
	public static Item steel_nn_leggings;
	public static Item steel_nn_boots;
	public static Item steel_b_helmet;
	public static Item steel_b_chestplate;
	public static Item steel_b_leggings;
	public static Item steel_b_boots;
	public static Item steel_bb_helmet;
	public static Item steel_bb_chestplate;
	public static Item steel_bb_leggings;
	public static Item steel_bb_boots;
	public static Item steel_t_helmet;
	public static Item steel_t_chestplate;
	public static Item steel_t_leggings;
	public static Item steel_t_boots;
	public static Item steel_tt_helmet;
	public static Item steel_tt_chestplate;
	public static Item steel_tt_leggings;
	public static Item steel_tt_boots;
	public static Item steel_cn_helmet;
	public static Item steel_cn_chestplate;
	public static Item steel_cn_leggings;
	public static Item steel_cn_boots;
	public static Item steel_cb_helmet;
	public static Item steel_cb_chestplate;
	public static Item steel_cb_leggings;
	public static Item steel_cb_boots;
	public static Item steel_ct_helmet;
	public static Item steel_ct_chestplate;
	public static Item steel_ct_leggings;
	public static Item steel_ct_boots;
	public static Item steel_nb_helmet;
	public static Item steel_nb_chestplate;
	public static Item steel_nb_leggings;
	public static Item steel_nb_boots;
	public static Item steel_nt_helmet;
	public static Item steel_nt_chestplate;
	public static Item steel_nt_leggings;
	public static Item steel_nt_boots;
	public static Item steel_bt_helmet;
	public static Item steel_bt_chestplate;
	public static Item steel_bt_leggings;
	public static Item steel_bt_boots;

public static Item rose_gold_pick;
public static Item rose_gold_shovel;
public static Item rose_gold_sword;
public static Item rose_gold_hoe;
public static Item rose_gold_axe;
	
public static Item mod_iron_pick;
public static Item mod_iron_shovel;
public static Item mod_iron_sword;
public static Item mod_iron_hoe;
public static Item mod_iron_axe;
	
public static Item copper_pick;
public static Item brassz_pick;
public static Item brasszz_pick;
public static Item bronzet_pick;
public static Item bronzett_pick;
public static Item bronzetz_pick;
public static Item steelc_pick;
public static Item steelcc_pick;
public static Item steeln_pick;
public static Item steelnn_pick;
public static Item steelb_pick;
public static Item steelbb_pick;
public static Item steelt_pick;
public static Item steeltt_pick;
public static Item steelcn_pick;
public static Item steelcb_pick;
public static Item steelct_pick;
public static Item steelnb_pick;
public static Item steelnt_pick;
public static Item steelbt_pick;
public static Item copper_sword;
public static Item brassz_sword;
public static Item brasszz_sword;
public static Item bronzet_sword;
public static Item bronzett_sword;
public static Item bronzetz_sword;
public static Item steelc_sword;
public static Item steelcc_sword;
public static Item steeln_sword;
public static Item steelnn_sword;
public static Item steelb_sword;
public static Item steelbb_sword;
public static Item steelt_sword;
public static Item steeltt_sword;
public static Item steelcn_sword;
public static Item steelcb_sword;
public static Item steelct_sword;
public static Item steelnb_sword;
public static Item steelnt_sword;
public static Item steelbt_sword;
public static Item copper_hoe;
public static Item brassz_hoe;
public static Item brasszz_hoe;
public static Item bronzet_hoe;
public static Item bronzett_hoe;
public static Item bronzetz_hoe;
public static Item steelc_hoe;
public static Item steelcc_hoe;
public static Item steeln_hoe;
public static Item steelnn_hoe;
public static Item steelb_hoe;
public static Item steelbb_hoe;
public static Item steelt_hoe;
public static Item steeltt_hoe;
public static Item steelcn_hoe;
public static Item steelcb_hoe;
public static Item steelct_hoe;
public static Item steelnb_hoe;
public static Item steelnt_hoe;
public static Item steelbt_hoe;
public static Item copper_shovel;
public static Item brassz_shovel;
public static Item brasszz_shovel;
public static Item bronzet_shovel;
public static Item bronzett_shovel;
public static Item bronzetz_shovel;
public static Item steelc_shovel;
public static Item steelcc_shovel;
public static Item steeln_shovel;
public static Item steelnn_shovel;
public static Item steelb_shovel;
public static Item steelbb_shovel;
public static Item steelt_shovel;
public static Item steeltt_shovel;
public static Item steelcn_shovel;
public static Item steelcb_shovel;
public static Item steelct_shovel;
public static Item steelnb_shovel;
public static Item steelnt_shovel;
public static Item steelbt_shovel;
public static Item copper_axe;
public static Item brassz_axe;
public static Item brasszz_axe;
public static Item bronzet_axe;
public static Item bronzett_axe;
public static Item bronzetz_axe;
public static Item steelc_axe;
public static Item steelcc_axe;
public static Item steeln_axe;
public static Item steelnn_axe;
public static Item steelb_axe;
public static Item steelbb_axe;
public static Item steelt_axe;
public static Item steeltt_axe;
public static Item steelcn_axe;
public static Item steelcb_axe;
public static Item steelct_axe;
public static Item steelnb_axe;
public static Item steelnt_axe;
public static Item steelbt_axe;

public static void mainRegistry(){
	initializeItem();
	registerItem();
}
 
public static void initializeItem(){
	
	rose_gold_helmet = new rose_gold_armor(rose_gold_armor_material, MainRegistry.proxy.addArmor("rose_gold_armor"), 0).setUnlocalizedName("rose_gold_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":rose_gold_helmet");
	rose_gold_chestplate = new rose_gold_armor(rose_gold_armor_material, MainRegistry.proxy.addArmor("rose_gold_armor"), 1).setUnlocalizedName("rose_gold_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":rose_gold_chestplate");
	rose_gold_leggings = new rose_gold_armor(rose_gold_armor_material, MainRegistry.proxy.addArmor("rose_gold_armor"), 2).setUnlocalizedName("rose_gold_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":rose_gold_leggings");
	rose_gold_boots = new rose_gold_armor(rose_gold_armor_material, MainRegistry.proxy.addArmor("rose_gold_armor"), 3).setUnlocalizedName("rose_gold_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":rose_gold_boots");
	
	mod_iron_helmet = new mod_iron_armor(iron_armor_material, MainRegistry.proxy.addArmor("mod_iron_armor"), 0).setUnlocalizedName("mod_iron_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":mod_iron_helmet");
	mod_iron_chestplate = new mod_iron_armor(iron_armor_material, MainRegistry.proxy.addArmor("mod_iron_armor"), 1).setUnlocalizedName("mod_iron_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":mod_iron_chestplate");
	mod_iron_leggings = new mod_iron_armor(iron_armor_material, MainRegistry.proxy.addArmor("mod_iron_armor"), 2).setUnlocalizedName("mod_iron_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":mod_iron_leggings");
	mod_iron_boots = new mod_iron_armor(iron_armor_material, MainRegistry.proxy.addArmor("mod_iron_armor"), 3).setUnlocalizedName("mod_iron_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":mod_iron_boots");
	
	copper_helmet = new copper_armor(copper_armor_material, MainRegistry.proxy.addArmor("copper_armor"), 0).setUnlocalizedName("copper_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":copper_helmet");
	copper_chestplate = new copper_armor(copper_armor_material, MainRegistry.proxy.addArmor("copper_armor"), 1).setUnlocalizedName("copper_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":copper_chestplate");
	copper_leggings = new copper_armor(copper_armor_material, MainRegistry.proxy.addArmor("copper_armor"), 2).setUnlocalizedName("copper_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":copper_leggings");
	copper_boots = new copper_armor(copper_armor_material, MainRegistry.proxy.addArmor("copper_armor"), 3).setUnlocalizedName("copper_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":copper_boots");
	brass_z_helmet = new brass_z_armor(brass_z_armor_material, MainRegistry.proxy.addArmor("brass_z_armor"), 0).setUnlocalizedName("brass_z_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_z_helmet");
	brass_z_chestplate = new brass_z_armor(brass_z_armor_material, MainRegistry.proxy.addArmor("brass_z_armor"), 1).setUnlocalizedName("brass_z_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_z_chestplate");
	brass_z_leggings = new brass_z_armor(brass_z_armor_material, MainRegistry.proxy.addArmor("brass_z_armor"), 2).setUnlocalizedName("brass_z_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_z_leggings");
	brass_z_boots = new brass_z_armor(brass_z_armor_material, MainRegistry.proxy.addArmor("brass_z_armor"), 3).setUnlocalizedName("brass_z_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_z_boots");
	brass_zz_helmet = new brass_zz_armor(brass_zz_armor_material, MainRegistry.proxy.addArmor("brass_zz_armor"), 0).setUnlocalizedName("brass_zz_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_zz_helmet");
	brass_zz_chestplate = new brass_zz_armor(brass_zz_armor_material, MainRegistry.proxy.addArmor("brass_zz_armor"), 1).setUnlocalizedName("brass_zz_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_zz_chestplate");
	brass_zz_leggings = new brass_zz_armor(brass_zz_armor_material, MainRegistry.proxy.addArmor("brass_zz_armor"), 2).setUnlocalizedName("brass_zz_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_zz_leggings");
	brass_zz_boots = new brass_zz_armor(brass_zz_armor_material, MainRegistry.proxy.addArmor("brass_zz_armor"), 3).setUnlocalizedName("brass_zz_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brass_zz_boots");
	bronze_t_helmet = new bronze_t_armor(bronze_t_armor_material, MainRegistry.proxy.addArmor("bronze_t_armor"), 0).setUnlocalizedName("bronze_t_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_t_helmet");
	bronze_t_chestplate = new bronze_t_armor(bronze_t_armor_material, MainRegistry.proxy.addArmor("bronze_t_armor"), 1).setUnlocalizedName("bronze_t_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_t_chestplate");
	bronze_t_leggings = new bronze_t_armor(bronze_t_armor_material, MainRegistry.proxy.addArmor("bronze_t_armor"), 2).setUnlocalizedName("bronze_t_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_t_leggings");
	bronze_t_boots = new bronze_t_armor(bronze_t_armor_material, MainRegistry.proxy.addArmor("bronze_t_armor"), 3).setUnlocalizedName("bronze_t_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_t_boots");
	bronze_tt_helmet = new bronze_tt_armor(bronze_tt_armor_material, MainRegistry.proxy.addArmor("bronze_tt_armor"), 0).setUnlocalizedName("bronze_tt_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tt_helmet");
	bronze_tt_chestplate = new bronze_tt_armor(bronze_tt_armor_material, MainRegistry.proxy.addArmor("bronze_tt_armor"), 1).setUnlocalizedName("bronze_tt_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tt_chestplate");
	bronze_tt_leggings = new bronze_tt_armor(bronze_tt_armor_material, MainRegistry.proxy.addArmor("bronze_tt_armor"), 2).setUnlocalizedName("bronze_tt_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tt_leggings");
	bronze_tt_boots = new bronze_tt_armor(bronze_tt_armor_material, MainRegistry.proxy.addArmor("bronze_tt_armor"), 3).setUnlocalizedName("bronze_tt_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tt_boots");
	bronze_tz_helmet = new bronze_tz_armor(bronze_tz_armor_material, MainRegistry.proxy.addArmor("bronze_tz_armor"), 0).setUnlocalizedName("bronze_tz_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tz_helmet");
	bronze_tz_chestplate = new bronze_tz_armor(bronze_tz_armor_material, MainRegistry.proxy.addArmor("bronze_tz_armor"), 1).setUnlocalizedName("bronze_tz_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tz_chestplate");
	bronze_tz_leggings = new bronze_tz_armor(bronze_tz_armor_material, MainRegistry.proxy.addArmor("bronze_tz_armor"), 2).setUnlocalizedName("bronze_tz_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tz_leggings");
	bronze_tz_boots = new bronze_tz_armor(bronze_tz_armor_material, MainRegistry.proxy.addArmor("bronze_tz_armor"), 3).setUnlocalizedName("bronze_tz_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronze_tz_boots");
	steel_c_helmet = new steel_c_armor(steel_c_armor_material, MainRegistry.proxy.addArmor("steel_c_armor"), 0).setUnlocalizedName("steel_c_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_c_helmet");
	steel_c_chestplate = new steel_c_armor(steel_c_armor_material, MainRegistry.proxy.addArmor("steel_c_armor"), 1).setUnlocalizedName("steel_c_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_c_chestplate");
	steel_c_leggings = new steel_c_armor(steel_c_armor_material, MainRegistry.proxy.addArmor("steel_c_armor"), 2).setUnlocalizedName("steel_c_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_c_leggings");
	steel_c_boots = new steel_c_armor(steel_c_armor_material, MainRegistry.proxy.addArmor("steel_c_armor"), 3).setUnlocalizedName("steel_c_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_c_boots");
	steel_cc_helmet = new steel_cc_armor(steel_cc_armor_material, MainRegistry.proxy.addArmor("steel_cc_armor"), 0).setUnlocalizedName("steel_cc_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cc_helmet");
	steel_cc_chestplate = new steel_cc_armor(steel_cc_armor_material, MainRegistry.proxy.addArmor("steel_cc_armor"), 1).setUnlocalizedName("steel_cc_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cc_chestplate");
	steel_cc_leggings = new steel_cc_armor(steel_cc_armor_material, MainRegistry.proxy.addArmor("steel_cc_armor"), 2).setUnlocalizedName("steel_cc_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cc_leggings");
	steel_cc_boots = new steel_cc_armor(steel_cc_armor_material, MainRegistry.proxy.addArmor("steel_cc_armor"), 3).setUnlocalizedName("steel_cc_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cc_boots");
	steel_n_helmet = new steel_n_armor(steel_n_armor_material, MainRegistry.proxy.addArmor("steel_n_armor"), 0).setUnlocalizedName("steel_n_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_n_helmet");
	steel_n_chestplate = new steel_n_armor(steel_n_armor_material, MainRegistry.proxy.addArmor("steel_n_armor"), 1).setUnlocalizedName("steel_n_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_n_chestplate");
	steel_n_leggings = new steel_n_armor(steel_n_armor_material, MainRegistry.proxy.addArmor("steel_n_armor"), 2).setUnlocalizedName("steel_n_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_n_leggings");
	steel_n_boots = new steel_n_armor(steel_n_armor_material, MainRegistry.proxy.addArmor("steel_n_armor"), 3).setUnlocalizedName("steel_n_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_n_boots");
	steel_nn_helmet = new steel_nn_armor(steel_nn_armor_material, MainRegistry.proxy.addArmor("steel_nn_armor"), 0).setUnlocalizedName("steel_nn_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nn_helmet");
	steel_nn_chestplate = new steel_nn_armor(steel_nn_armor_material, MainRegistry.proxy.addArmor("steel_nn_armor"), 1).setUnlocalizedName("steel_nn_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nn_chestplate");
	steel_nn_leggings = new steel_nn_armor(steel_nn_armor_material, MainRegistry.proxy.addArmor("steel_nn_armor"), 2).setUnlocalizedName("steel_nn_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nn_leggings");
	steel_nn_boots = new steel_nn_armor(steel_nn_armor_material, MainRegistry.proxy.addArmor("steel_nn_armor"), 3).setUnlocalizedName("steel_nn_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nn_boots");
	steel_b_helmet = new steel_b_armor(steel_b_armor_material, MainRegistry.proxy.addArmor("steel_b_armor"), 0).setUnlocalizedName("steel_b_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_b_helmet");
	steel_b_chestplate = new steel_b_armor(steel_b_armor_material, MainRegistry.proxy.addArmor("steel_b_armor"), 1).setUnlocalizedName("steel_b_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_b_chestplate");
	steel_b_leggings = new steel_b_armor(steel_b_armor_material, MainRegistry.proxy.addArmor("steel_b_armor"), 2).setUnlocalizedName("steel_b_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_b_leggings");
	steel_b_boots = new steel_b_armor(steel_b_armor_material, MainRegistry.proxy.addArmor("steel_b_armor"), 3).setUnlocalizedName("steel_b_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_b_boots");
	steel_bb_helmet = new steel_bb_armor(steel_bb_armor_material, MainRegistry.proxy.addArmor("steel_bb_armor"), 0).setUnlocalizedName("steel_bb_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bb_helmet");
	steel_bb_chestplate = new steel_bb_armor(steel_bb_armor_material, MainRegistry.proxy.addArmor("steel_bb_armor"), 1).setUnlocalizedName("steel_bb_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bb_chestplate");
	steel_bb_leggings = new steel_bb_armor(steel_bb_armor_material, MainRegistry.proxy.addArmor("steel_bb_armor"), 2).setUnlocalizedName("steel_bb_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bb_leggings");
	steel_bb_boots = new steel_bb_armor(steel_bb_armor_material, MainRegistry.proxy.addArmor("steel_bb_armor"), 3).setUnlocalizedName("steel_bb_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bb_boots");
	steel_t_helmet = new steel_t_armor(steel_t_armor_material, MainRegistry.proxy.addArmor("steel_t_armor"), 0).setUnlocalizedName("steel_t_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_t_helmet");
	steel_t_chestplate = new steel_t_armor(steel_t_armor_material, MainRegistry.proxy.addArmor("steel_t_armor"), 1).setUnlocalizedName("steel_t_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_t_chestplate");
	steel_t_leggings = new steel_t_armor(steel_t_armor_material, MainRegistry.proxy.addArmor("steel_t_armor"), 2).setUnlocalizedName("steel_t_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_t_leggings");
	steel_t_boots = new steel_t_armor(steel_t_armor_material, MainRegistry.proxy.addArmor("steel_t_armor"), 3).setUnlocalizedName("steel_t_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_t_boots");
	steel_tt_helmet = new steel_tt_armor(steel_tt_armor_material, MainRegistry.proxy.addArmor("steel_tt_armor"), 0).setUnlocalizedName("steel_tt_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_tt_helmet");
	steel_tt_chestplate = new steel_tt_armor(steel_tt_armor_material, MainRegistry.proxy.addArmor("steel_tt_armor"), 1).setUnlocalizedName("steel_tt_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_tt_chestplate");
	steel_tt_leggings = new steel_tt_armor(steel_tt_armor_material, MainRegistry.proxy.addArmor("steel_tt_armor"), 2).setUnlocalizedName("steel_tt_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_tt_leggings");
	steel_tt_boots = new steel_tt_armor(steel_tt_armor_material, MainRegistry.proxy.addArmor("steel_tt_armor"), 3).setUnlocalizedName("steel_tt_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_tt_boots");
	steel_cn_helmet = new steel_cn_armor(steel_cn_armor_material, MainRegistry.proxy.addArmor("steel_cn_armor"), 0).setUnlocalizedName("steel_cn_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cn_helmet");
	steel_cn_chestplate = new steel_cn_armor(steel_cn_armor_material, MainRegistry.proxy.addArmor("steel_cn_armor"), 1).setUnlocalizedName("steel_cn_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cn_chestplate");
	steel_cn_leggings = new steel_cn_armor(steel_cn_armor_material, MainRegistry.proxy.addArmor("steel_cn_armor"), 2).setUnlocalizedName("steel_cn_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cn_leggings");
	steel_cn_boots = new steel_cn_armor(steel_cn_armor_material, MainRegistry.proxy.addArmor("steel_cn_armor"), 3).setUnlocalizedName("steel_cn_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cn_boots");
	steel_cb_helmet = new steel_cb_armor(steel_cb_armor_material, MainRegistry.proxy.addArmor("steel_cb_armor"), 0).setUnlocalizedName("steel_cb_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cb_helmet");
	steel_cb_chestplate = new steel_cb_armor(steel_cb_armor_material, MainRegistry.proxy.addArmor("steel_cb_armor"), 1).setUnlocalizedName("steel_cb_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cb_chestplate");
	steel_cb_leggings = new steel_cb_armor(steel_cb_armor_material, MainRegistry.proxy.addArmor("steel_cb_armor"), 2).setUnlocalizedName("steel_cb_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cb_leggings");
	steel_cb_boots = new steel_cb_armor(steel_cb_armor_material, MainRegistry.proxy.addArmor("steel_cb_armor"), 3).setUnlocalizedName("steel_cb_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_cb_boots");
	steel_ct_helmet = new steel_ct_armor(steel_ct_armor_material, MainRegistry.proxy.addArmor("steel_ct_armor"), 0).setUnlocalizedName("steel_ct_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_ct_helmet");
	steel_ct_chestplate = new steel_ct_armor(steel_ct_armor_material, MainRegistry.proxy.addArmor("steel_ct_armor"), 1).setUnlocalizedName("steel_ct_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_ct_chestplate");
	steel_ct_leggings = new steel_ct_armor(steel_ct_armor_material, MainRegistry.proxy.addArmor("steel_ct_armor"), 2).setUnlocalizedName("steel_ct_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_ct_leggings");
	steel_ct_boots = new steel_ct_armor(steel_ct_armor_material, MainRegistry.proxy.addArmor("steel_ct_armor"), 3).setUnlocalizedName("steel_ct_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_ct_boots");
	steel_nb_helmet = new steel_nb_armor(steel_nb_armor_material, MainRegistry.proxy.addArmor("steel_nb_armor"), 0).setUnlocalizedName("steel_nb_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nb_helmet");
	steel_nb_chestplate = new steel_nb_armor(steel_nb_armor_material, MainRegistry.proxy.addArmor("steel_nb_armor"), 1).setUnlocalizedName("steel_nb_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nb_chestplate");
	steel_nb_leggings = new steel_nb_armor(steel_nb_armor_material, MainRegistry.proxy.addArmor("steel_nb_armor"), 2).setUnlocalizedName("steel_nb_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nb_leggings");
	steel_nb_boots = new steel_nb_armor(steel_nb_armor_material, MainRegistry.proxy.addArmor("steel_nb_armor"), 3).setUnlocalizedName("steel_nb_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nb_boots");
	steel_nt_helmet = new steel_nt_armor(steel_nt_armor_material, MainRegistry.proxy.addArmor("steel_nt_armor"), 0).setUnlocalizedName("steel_nt_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nt_helmet");
	steel_nt_chestplate = new steel_nt_armor(steel_nt_armor_material, MainRegistry.proxy.addArmor("steel_nt_armor"), 1).setUnlocalizedName("steel_nt_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nt_chestplate");
	steel_nt_leggings = new steel_nt_armor(steel_nt_armor_material, MainRegistry.proxy.addArmor("steel_nt_armor"), 2).setUnlocalizedName("steel_nt_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nt_leggings");
	steel_nt_boots = new steel_nt_armor(steel_nt_armor_material, MainRegistry.proxy.addArmor("steel_nt_armor"), 3).setUnlocalizedName("steel_nt_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_nt_boots");
	steel_bt_helmet = new steel_bt_armor(steel_bt_armor_material, MainRegistry.proxy.addArmor("steel_bt_armor"), 0).setUnlocalizedName("steel_bt_helmet").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bt_helmet");
	steel_bt_chestplate = new steel_bt_armor(steel_bt_armor_material, MainRegistry.proxy.addArmor("steel_bt_armor"), 1).setUnlocalizedName("steel_bt_chestplate").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bt_chestplate");
	steel_bt_leggings = new steel_bt_armor(steel_bt_armor_material, MainRegistry.proxy.addArmor("steel_bt_armor"), 2).setUnlocalizedName("steel_bt_leggings").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bt_leggings");
	steel_bt_boots = new steel_bt_armor(steel_bt_armor_material, MainRegistry.proxy.addArmor("steel_bt_armor"), 3).setUnlocalizedName("steel_bt_boots").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steel_bt_boots");

rose_gold_pick = new CopperPick(rose_gold).setUnlocalizedName("rose_gold_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":rose_gold_pick");
rose_gold_axe = new CopperAxe(rose_gold).setUnlocalizedName("rose_gold_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":rose_gold_axe");
rose_gold_shovel = new CopperShovel(rose_gold).setUnlocalizedName("rose_gold_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":rose_gold_shovel");
rose_gold_hoe = new CopperHoe(rose_gold).setUnlocalizedName("rose_gold_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":rose_gold_hoe");
rose_gold_sword = new CopperSword(rose_gold).setUnlocalizedName("rose_gold_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":rose_gold_sword");
	
mod_iron_pick = new CopperPick(iron).setUnlocalizedName("mod_iron_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":mod_iron_pick");
mod_iron_axe = new CopperAxe(iron).setUnlocalizedName("mod_iron_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":mod_iron_axe");
mod_iron_shovel = new CopperShovel(iron).setUnlocalizedName("mod_iron_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":mod_iron_shovel");
mod_iron_hoe = new CopperHoe(iron).setUnlocalizedName("mod_iron_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":mod_iron_hoe");
mod_iron_sword = new CopperSword(iron).setUnlocalizedName("mod_iron_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":mod_iron_sword");
	
copper_pick = new CopperPick(copper).setUnlocalizedName("copper_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":copper_pick");
brassz_pick = new BrasszPick(brassz).setUnlocalizedName("brassz_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brassz_pick");
brasszz_pick = new BrasszzPick(brasszz).setUnlocalizedName("brasszz_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brasszz_pick");
bronzet_pick = new BronzetPick(bronzet).setUnlocalizedName("bronzet_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzet_pick");
bronzett_pick = new BronzettPick(bronzett).setUnlocalizedName("bronzett_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzett_pick");
bronzetz_pick = new BronzetzPick(bronzetz).setUnlocalizedName("bronzetz_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzetz_pick");
steelc_pick = new SteelcPick(steelc).setUnlocalizedName("steelc_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelc_pick");
steelcc_pick = new SteelccPick(steelcc).setUnlocalizedName("steelcc_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcc_pick");
steeln_pick = new SteelnPick(steeln).setUnlocalizedName("steeln_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeln_pick");
steelnn_pick = new SteelnnPick(steelnn).setUnlocalizedName("steelnn_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnn_pick");
steelb_pick = new SteelbPick(steelb).setUnlocalizedName("steelb_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelb_pick");
steelbb_pick = new SteelbbPick(steelbb).setUnlocalizedName("steelbb_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbb_pick");
steelt_pick = new SteeltPick(steelt).setUnlocalizedName("steelt_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelt_pick");
steeltt_pick = new SteelttPick(steeltt).setUnlocalizedName("steeltt_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeltt_pick");
steelcn_pick = new SteelcnPick(steelcn).setUnlocalizedName("steelcn_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcn_pick");
steelcb_pick = new SteelcbPick(steelcb).setUnlocalizedName("steelcb_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcb_pick");
steelct_pick = new SteelctPick(steelct).setUnlocalizedName("steelct_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelct_pick");
steelnb_pick = new SteelnbPick(steelnb).setUnlocalizedName("steelnb_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnb_pick");
steelnt_pick = new SteelntPick(steelnt).setUnlocalizedName("steelnt_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnt_pick");
steelbt_pick = new SteelbtPick(steelbt).setUnlocalizedName("steelbt_pick").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbt_pick");
copper_sword = new CopperSword(copper).setUnlocalizedName("copper_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":copper_sword");
brassz_sword = new BrasszSword(brassz).setUnlocalizedName("brassz_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brassz_sword");
brasszz_sword = new BrasszzSword(brasszz).setUnlocalizedName("brasszz_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":brasszz_sword");
bronzet_sword = new BronzetSword(bronzet).setUnlocalizedName("bronzet_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronzet_sword");
bronzett_sword = new BronzettSword(bronzett).setUnlocalizedName("bronzett_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronzett_sword");
bronzetz_sword = new BronzetzSword(bronzetz).setUnlocalizedName("bronzetz_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":bronzetz_sword");
steelc_sword = new SteelcSword(steelc).setUnlocalizedName("steelc_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelc_sword");
steelcc_sword = new SteelccSword(steelcc).setUnlocalizedName("steelcc_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelcc_sword");
steeln_sword = new SteelnSword(steeln).setUnlocalizedName("steeln_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steeln_sword");
steelnn_sword = new SteelnnSword(steelnn).setUnlocalizedName("steelnn_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelnn_sword");
steelb_sword = new SteelbSword(steelb).setUnlocalizedName("steelb_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelb_sword");
steelbb_sword = new SteelbbSword(steelbb).setUnlocalizedName("steelbb_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelbb_sword");
steelt_sword = new SteeltSword(steelt).setUnlocalizedName("steelt_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelt_sword");
steeltt_sword = new SteelttSword(steeltt).setUnlocalizedName("steeltt_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steeltt_sword");
steelcn_sword = new SteelcnSword(steelcn).setUnlocalizedName("steelcn_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelcn_sword");
steelcb_sword = new SteelcbSword(steelcb).setUnlocalizedName("steelcb_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelcb_sword");
steelct_sword = new SteelctSword(steelct).setUnlocalizedName("steelct_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelct_sword");
steelnb_sword = new SteelnbSword(steelnb).setUnlocalizedName("steelnb_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelnb_sword");
steelnt_sword = new SteelntSword(steelnt).setUnlocalizedName("steelnt_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelnt_sword");
steelbt_sword = new SteelbtSword(steelbt).setUnlocalizedName("steelbt_sword").setCreativeTab(CreativeTabs.tabCombat).setTextureName(Ref.MODID + ":steelbt_sword");
copper_hoe = new CopperHoe(copper).setUnlocalizedName("copper_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":copper_hoe");
brassz_hoe = new BrasszHoe(brassz).setUnlocalizedName("brassz_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brassz_hoe");
brasszz_hoe = new BrasszzHoe(brasszz).setUnlocalizedName("brasszz_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brasszz_hoe");
bronzet_hoe = new BronzetHoe(bronzet).setUnlocalizedName("bronzet_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzet_hoe");
bronzett_hoe = new BronzettHoe(bronzett).setUnlocalizedName("bronzett_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzett_hoe");
bronzetz_hoe = new BronzetzHoe(bronzetz).setUnlocalizedName("bronzetz_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzetz_hoe");
steelc_hoe = new SteelcHoe(steelc).setUnlocalizedName("steelc_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelc_hoe");
steelcc_hoe = new SteelccHoe(steelcc).setUnlocalizedName("steelcc_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcc_hoe");
steeln_hoe = new SteelnHoe(steeln).setUnlocalizedName("steeln_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeln_hoe");
steelnn_hoe = new SteelnnHoe(steelnn).setUnlocalizedName("steelnn_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnn_hoe");
steelb_hoe = new SteelbHoe(steelb).setUnlocalizedName("steelb_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelb_hoe");
steelbb_hoe = new SteelbbHoe(steelbb).setUnlocalizedName("steelbb_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbb_hoe");
steelt_hoe = new SteeltHoe(steelt).setUnlocalizedName("steelt_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelt_hoe");
steeltt_hoe = new SteelttHoe(steeltt).setUnlocalizedName("steeltt_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeltt_hoe");
steelcn_hoe = new SteelcnHoe(steelcn).setUnlocalizedName("steelcn_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcn_hoe");
steelcb_hoe = new SteelcbHoe(steelcb).setUnlocalizedName("steelcb_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcb_hoe");
steelct_hoe = new SteelctHoe(steelct).setUnlocalizedName("steelct_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelct_hoe");
steelnb_hoe = new SteelnbHoe(steelnb).setUnlocalizedName("steelnb_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnb_hoe");
steelnt_hoe = new SteelntHoe(steelnt).setUnlocalizedName("steelnt_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnt_hoe");
steelbt_hoe = new SteelbtHoe(steelbt).setUnlocalizedName("steelbt_hoe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbt_hoe");
copper_shovel = new CopperShovel(copper).setUnlocalizedName("copper_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":copper_shovel");
brassz_shovel = new BrasszShovel(brassz).setUnlocalizedName("brassz_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brassz_shovel");
brasszz_shovel = new BrasszzShovel(brasszz).setUnlocalizedName("brasszz_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brasszz_shovel");
bronzet_shovel = new BronzetShovel(bronzet).setUnlocalizedName("bronzet_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzet_shovel");
bronzett_shovel = new BronzettShovel(bronzett).setUnlocalizedName("bronzett_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzett_shovel");
bronzetz_shovel = new BronzetzShovel(bronzetz).setUnlocalizedName("bronzetz_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzetz_shovel");
steelc_shovel = new SteelcShovel(steelc).setUnlocalizedName("steelc_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelc_shovel");
steelcc_shovel = new SteelccShovel(steelcc).setUnlocalizedName("steelcc_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcc_shovel");
steeln_shovel = new SteelnShovel(steeln).setUnlocalizedName("steeln_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeln_shovel");
steelnn_shovel = new SteelnnShovel(steelnn).setUnlocalizedName("steelnn_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnn_shovel");
steelb_shovel = new SteelbShovel(steelb).setUnlocalizedName("steelb_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelb_shovel");
steelbb_shovel = new SteelbbShovel(steelbb).setUnlocalizedName("steelbb_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbb_shovel");
steelt_shovel = new SteeltShovel(steelt).setUnlocalizedName("steelt_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelt_shovel");
steeltt_shovel = new SteelttShovel(steeltt).setUnlocalizedName("steeltt_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeltt_shovel");
steelcn_shovel = new SteelcnShovel(steelcn).setUnlocalizedName("steelcn_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcn_shovel");
steelcb_shovel = new SteelcbShovel(steelcb).setUnlocalizedName("steelcb_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcb_shovel");
steelct_shovel = new SteelctShovel(steelct).setUnlocalizedName("steelct_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelct_shovel");
steelnb_shovel = new SteelnbShovel(steelnb).setUnlocalizedName("steelnb_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnb_shovel");
steelnt_shovel = new SteelntShovel(steelnt).setUnlocalizedName("steelnt_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnt_shovel");
steelbt_shovel = new SteelbtShovel(steelbt).setUnlocalizedName("steelbt_shovel").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbt_shovel");
copper_axe = new CopperAxe(copper).setUnlocalizedName("copper_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":copper_axe");
brassz_axe = new BrasszAxe(brassz).setUnlocalizedName("brassz_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brassz_axe");
brasszz_axe = new BrasszzAxe(brasszz).setUnlocalizedName("brasszz_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":brasszz_axe");
bronzet_axe = new BronzetAxe(bronzet).setUnlocalizedName("bronzet_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzet_axe");
bronzett_axe = new BronzettAxe(bronzett).setUnlocalizedName("bronzett_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzett_axe");
bronzetz_axe = new BronzetzAxe(bronzetz).setUnlocalizedName("bronzetz_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":bronzetz_axe");
steelc_axe = new SteelcAxe(steelc).setUnlocalizedName("steelc_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelc_axe");
steelcc_axe = new SteelccAxe(steelcc).setUnlocalizedName("steelcc_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcc_axe");
steeln_axe = new SteelnAxe(steeln).setUnlocalizedName("steeln_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeln_axe");
steelnn_axe = new SteelnnAxe(steelnn).setUnlocalizedName("steelnn_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnn_axe");
steelb_axe = new SteelbAxe(steelb).setUnlocalizedName("steelb_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelb_axe");
steelbb_axe = new SteelbbAxe(steelbb).setUnlocalizedName("steelbb_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbb_axe");
steelt_axe = new SteeltAxe(steelt).setUnlocalizedName("steelt_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelt_axe");
steeltt_axe = new SteelttAxe(steeltt).setUnlocalizedName("steeltt_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steeltt_axe");
steelcn_axe = new SteelcnAxe(steelcn).setUnlocalizedName("steelcn_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcn_axe");
steelcb_axe = new SteelcbAxe(steelcb).setUnlocalizedName("steelcb_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelcb_axe");
steelct_axe = new SteelctAxe(steelct).setUnlocalizedName("steelct_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelct_axe");
steelnb_axe = new SteelnbAxe(steelnb).setUnlocalizedName("steelnb_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnb_axe");
steelnt_axe = new SteelntAxe(steelnt).setUnlocalizedName("steelnt_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelnt_axe");
steelbt_axe = new SteelbtAxe(steelbt).setUnlocalizedName("steelbt_axe").setCreativeTab(CreativeTabs.tabTools).setTextureName(Ref.MODID + ":steelbt_axe");

 }
 
public static void registerItem(){

	GameRegistry.registerItem(rose_gold_helmet, rose_gold_helmet.getUnlocalizedName());
	GameRegistry.registerItem(rose_gold_chestplate, rose_gold_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(rose_gold_leggings, rose_gold_leggings.getUnlocalizedName());
	GameRegistry.registerItem(rose_gold_boots, rose_gold_boots.getUnlocalizedName());

	GameRegistry.registerItem(mod_iron_helmet, mod_iron_helmet.getUnlocalizedName());
	GameRegistry.registerItem(mod_iron_chestplate, mod_iron_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(mod_iron_leggings, mod_iron_leggings.getUnlocalizedName());
	GameRegistry.registerItem(mod_iron_boots, mod_iron_boots.getUnlocalizedName());
	
	GameRegistry.registerItem(copper_helmet, copper_helmet.getUnlocalizedName());
	GameRegistry.registerItem(copper_chestplate, copper_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(copper_leggings, copper_leggings.getUnlocalizedName());
	GameRegistry.registerItem(copper_boots, copper_boots.getUnlocalizedName());
	GameRegistry.registerItem(brass_z_helmet, brass_z_helmet.getUnlocalizedName());
	GameRegistry.registerItem(brass_z_chestplate, brass_z_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(brass_z_leggings, brass_z_leggings.getUnlocalizedName());
	GameRegistry.registerItem(brass_z_boots, brass_z_boots.getUnlocalizedName());
	GameRegistry.registerItem(brass_zz_helmet, brass_zz_helmet.getUnlocalizedName());
	GameRegistry.registerItem(brass_zz_chestplate, brass_zz_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(brass_zz_leggings, brass_zz_leggings.getUnlocalizedName());
	GameRegistry.registerItem(brass_zz_boots, brass_zz_boots.getUnlocalizedName());
	GameRegistry.registerItem(bronze_t_helmet, bronze_t_helmet.getUnlocalizedName());
	GameRegistry.registerItem(bronze_t_chestplate, bronze_t_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(bronze_t_leggings, bronze_t_leggings.getUnlocalizedName());
	GameRegistry.registerItem(bronze_t_boots, bronze_t_boots.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tt_helmet, bronze_tt_helmet.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tt_chestplate, bronze_tt_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tt_leggings, bronze_tt_leggings.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tt_boots, bronze_tt_boots.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tz_helmet, bronze_tz_helmet.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tz_chestplate, bronze_tz_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tz_leggings, bronze_tz_leggings.getUnlocalizedName());
	GameRegistry.registerItem(bronze_tz_boots, bronze_tz_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_c_helmet, steel_c_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_c_chestplate, steel_c_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_c_leggings, steel_c_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_c_boots, steel_c_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_cc_helmet, steel_cc_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_cc_chestplate, steel_cc_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_cc_leggings, steel_cc_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_cc_boots, steel_cc_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_n_helmet, steel_n_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_n_chestplate, steel_n_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_n_leggings, steel_n_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_n_boots, steel_n_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_nn_helmet, steel_nn_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_nn_chestplate, steel_nn_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_nn_leggings, steel_nn_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_nn_boots, steel_nn_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_b_helmet, steel_b_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_b_chestplate, steel_b_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_b_leggings, steel_b_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_b_boots, steel_b_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_bb_helmet, steel_bb_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_bb_chestplate, steel_bb_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_bb_leggings, steel_bb_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_bb_boots, steel_bb_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_t_helmet, steel_t_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_t_chestplate, steel_t_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_t_leggings, steel_t_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_t_boots, steel_t_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_tt_helmet, steel_tt_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_tt_chestplate, steel_tt_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_tt_leggings, steel_tt_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_tt_boots, steel_tt_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_cn_helmet, steel_cn_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_cn_chestplate, steel_cn_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_cn_leggings, steel_cn_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_cn_boots, steel_cn_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_cb_helmet, steel_cb_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_cb_chestplate, steel_cb_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_cb_leggings, steel_cb_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_cb_boots, steel_cb_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_ct_helmet, steel_ct_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_ct_chestplate, steel_ct_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_ct_leggings, steel_ct_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_ct_boots, steel_ct_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_nb_helmet, steel_nb_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_nb_chestplate, steel_nb_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_nb_leggings, steel_nb_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_nb_boots, steel_nb_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_nt_helmet, steel_nt_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_nt_chestplate, steel_nt_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_nt_leggings, steel_nt_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_nt_boots, steel_nt_boots.getUnlocalizedName());
	GameRegistry.registerItem(steel_bt_helmet, steel_bt_helmet.getUnlocalizedName());
	GameRegistry.registerItem(steel_bt_chestplate, steel_bt_chestplate.getUnlocalizedName());
	GameRegistry.registerItem(steel_bt_leggings, steel_bt_leggings.getUnlocalizedName());
	GameRegistry.registerItem(steel_bt_boots, steel_bt_boots.getUnlocalizedName());

GameRegistry.registerItem(rose_gold_pick, rose_gold_pick.getUnlocalizedName());
GameRegistry.registerItem(rose_gold_axe, rose_gold_axe.getUnlocalizedName());
GameRegistry.registerItem(rose_gold_shovel, rose_gold_shovel.getUnlocalizedName());
GameRegistry.registerItem(rose_gold_hoe, rose_gold_hoe.getUnlocalizedName());
GameRegistry.registerItem(rose_gold_sword, rose_gold_sword.getUnlocalizedName());
	
GameRegistry.registerItem(mod_iron_pick, mod_iron_pick.getUnlocalizedName());
GameRegistry.registerItem(mod_iron_axe, mod_iron_axe.getUnlocalizedName());
GameRegistry.registerItem(mod_iron_shovel, mod_iron_shovel.getUnlocalizedName());
GameRegistry.registerItem(mod_iron_hoe, mod_iron_hoe.getUnlocalizedName());
GameRegistry.registerItem(mod_iron_sword, mod_iron_sword.getUnlocalizedName());
	
GameRegistry.registerItem(copper_pick, copper_pick.getUnlocalizedName());
GameRegistry.registerItem(brassz_pick, brassz_pick.getUnlocalizedName());
GameRegistry.registerItem(brasszz_pick, brasszz_pick.getUnlocalizedName());
GameRegistry.registerItem(bronzet_pick, bronzet_pick.getUnlocalizedName());
GameRegistry.registerItem(bronzett_pick, bronzett_pick.getUnlocalizedName());
GameRegistry.registerItem(bronzetz_pick, bronzetz_pick.getUnlocalizedName());
GameRegistry.registerItem(steelc_pick, steelc_pick.getUnlocalizedName());
GameRegistry.registerItem(steelcc_pick, steelcc_pick.getUnlocalizedName());
GameRegistry.registerItem(steeln_pick, steeln_pick.getUnlocalizedName());
GameRegistry.registerItem(steelnn_pick, steelnn_pick.getUnlocalizedName());
GameRegistry.registerItem(steelb_pick, steelb_pick.getUnlocalizedName());
GameRegistry.registerItem(steelbb_pick, steelbb_pick.getUnlocalizedName());
GameRegistry.registerItem(steelt_pick, steelt_pick.getUnlocalizedName());
GameRegistry.registerItem(steeltt_pick, steeltt_pick.getUnlocalizedName());
GameRegistry.registerItem(steelcn_pick, steelcn_pick.getUnlocalizedName());
GameRegistry.registerItem(steelcb_pick, steelcb_pick.getUnlocalizedName());
GameRegistry.registerItem(steelct_pick, steelct_pick.getUnlocalizedName());
GameRegistry.registerItem(steelnb_pick, steelnb_pick.getUnlocalizedName());
GameRegistry.registerItem(steelnt_pick, steelnt_pick.getUnlocalizedName());
GameRegistry.registerItem(steelbt_pick, steelbt_pick.getUnlocalizedName());
GameRegistry.registerItem(copper_sword, copper_sword.getUnlocalizedName());
GameRegistry.registerItem(brassz_sword, brassz_sword.getUnlocalizedName());
GameRegistry.registerItem(brasszz_sword, brasszz_sword.getUnlocalizedName());
GameRegistry.registerItem(bronzet_sword, bronzet_sword.getUnlocalizedName());
GameRegistry.registerItem(bronzett_sword, bronzett_sword.getUnlocalizedName());
GameRegistry.registerItem(bronzetz_sword, bronzetz_sword.getUnlocalizedName());
GameRegistry.registerItem(steelc_sword, steelc_sword.getUnlocalizedName());
GameRegistry.registerItem(steelcc_sword, steelcc_sword.getUnlocalizedName());
GameRegistry.registerItem(steeln_sword, steeln_sword.getUnlocalizedName());
GameRegistry.registerItem(steelnn_sword, steelnn_sword.getUnlocalizedName());
GameRegistry.registerItem(steelb_sword, steelb_sword.getUnlocalizedName());
GameRegistry.registerItem(steelbb_sword, steelbb_sword.getUnlocalizedName());
GameRegistry.registerItem(steelt_sword, steelt_sword.getUnlocalizedName());
GameRegistry.registerItem(steeltt_sword, steeltt_sword.getUnlocalizedName());
GameRegistry.registerItem(steelcn_sword, steelcn_sword.getUnlocalizedName());
GameRegistry.registerItem(steelcb_sword, steelcb_sword.getUnlocalizedName());
GameRegistry.registerItem(steelct_sword, steelct_sword.getUnlocalizedName());
GameRegistry.registerItem(steelnb_sword, steelnb_sword.getUnlocalizedName());
GameRegistry.registerItem(steelnt_sword, steelnt_sword.getUnlocalizedName());
GameRegistry.registerItem(steelbt_sword, steelbt_sword.getUnlocalizedName());
GameRegistry.registerItem(copper_hoe, copper_hoe.getUnlocalizedName());
GameRegistry.registerItem(brassz_hoe, brassz_hoe.getUnlocalizedName());
GameRegistry.registerItem(brasszz_hoe, brasszz_hoe.getUnlocalizedName());
GameRegistry.registerItem(bronzet_hoe, bronzet_hoe.getUnlocalizedName());
GameRegistry.registerItem(bronzett_hoe, bronzett_hoe.getUnlocalizedName());
GameRegistry.registerItem(bronzetz_hoe, bronzetz_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelc_hoe, steelc_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelcc_hoe, steelcc_hoe.getUnlocalizedName());
GameRegistry.registerItem(steeln_hoe, steeln_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelnn_hoe, steelnn_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelb_hoe, steelb_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelbb_hoe, steelbb_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelt_hoe, steelt_hoe.getUnlocalizedName());
GameRegistry.registerItem(steeltt_hoe, steeltt_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelcn_hoe, steelcn_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelcb_hoe, steelcb_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelct_hoe, steelct_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelnb_hoe, steelnb_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelnt_hoe, steelnt_hoe.getUnlocalizedName());
GameRegistry.registerItem(steelbt_hoe, steelbt_hoe.getUnlocalizedName());
GameRegistry.registerItem(copper_shovel, copper_shovel.getUnlocalizedName());
GameRegistry.registerItem(brassz_shovel, brassz_shovel.getUnlocalizedName());
GameRegistry.registerItem(brasszz_shovel, brasszz_shovel.getUnlocalizedName());
GameRegistry.registerItem(bronzet_shovel, bronzet_shovel.getUnlocalizedName());
GameRegistry.registerItem(bronzett_shovel, bronzett_shovel.getUnlocalizedName());
GameRegistry.registerItem(bronzetz_shovel, bronzetz_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelc_shovel, steelc_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelcc_shovel, steelcc_shovel.getUnlocalizedName());
GameRegistry.registerItem(steeln_shovel, steeln_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelnn_shovel, steelnn_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelb_shovel, steelb_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelbb_shovel, steelbb_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelt_shovel, steelt_shovel.getUnlocalizedName());
GameRegistry.registerItem(steeltt_shovel, steeltt_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelcn_shovel, steelcn_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelcb_shovel, steelcb_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelct_shovel, steelct_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelnb_shovel, steelnb_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelnt_shovel, steelnt_shovel.getUnlocalizedName());
GameRegistry.registerItem(steelbt_shovel, steelbt_shovel.getUnlocalizedName());
GameRegistry.registerItem(copper_axe, copper_axe.getUnlocalizedName());
GameRegistry.registerItem(brassz_axe, brassz_axe.getUnlocalizedName());
GameRegistry.registerItem(brasszz_axe, brasszz_axe.getUnlocalizedName());
GameRegistry.registerItem(bronzet_axe, bronzet_axe.getUnlocalizedName());
GameRegistry.registerItem(bronzett_axe, bronzett_axe.getUnlocalizedName());
GameRegistry.registerItem(bronzetz_axe, bronzetz_axe.getUnlocalizedName());
GameRegistry.registerItem(steelc_axe, steelc_axe.getUnlocalizedName());
GameRegistry.registerItem(steelcc_axe, steelcc_axe.getUnlocalizedName());
GameRegistry.registerItem(steeln_axe, steeln_axe.getUnlocalizedName());
GameRegistry.registerItem(steelnn_axe, steelnn_axe.getUnlocalizedName());
GameRegistry.registerItem(steelb_axe, steelb_axe.getUnlocalizedName());
GameRegistry.registerItem(steelbb_axe, steelbb_axe.getUnlocalizedName());
GameRegistry.registerItem(steelt_axe, steelt_axe.getUnlocalizedName());
GameRegistry.registerItem(steeltt_axe, steeltt_axe.getUnlocalizedName());
GameRegistry.registerItem(steelcn_axe, steelcn_axe.getUnlocalizedName());
GameRegistry.registerItem(steelcb_axe, steelcb_axe.getUnlocalizedName());
GameRegistry.registerItem(steelct_axe, steelct_axe.getUnlocalizedName());
GameRegistry.registerItem(steelnb_axe, steelnb_axe.getUnlocalizedName());
GameRegistry.registerItem(steelnt_axe, steelnt_axe.getUnlocalizedName());
GameRegistry.registerItem(steelbt_axe, steelbt_axe.getUnlocalizedName());

}
}