package com.fynal.Main;

import com.fynal.block.ModBlocks;
import com.fynal.item.ModItems;
import com.fynal.item.ModTools;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import cpw.mods.fml.common.registry.GameRegistry;

public class ToolCraftingManager {

	public static void mainRegistry(){
		addCrafting();
	}
	
	public static void addCrafting(){
		GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0)});
		
		GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(Items.iron_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(Items.iron_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(Items.iron_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(Items.iron_ingot, 1, 0)});

		GameRegistry.addRecipe(new ItemStack(ModTools.copper_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.copper_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.copper_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.copper_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.copper_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.copper_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.copper_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.copper_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_z_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_z_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_z_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_z_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_zz_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_zz_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_zz_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.brass_zz_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_t_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_t_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_t_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_t_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tt_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tt_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tt_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tt_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tz_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tz_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tz_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.bronze_tz_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_c_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_c_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_c_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_c_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cc_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cc_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cc_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cc_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_n_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_n_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_n_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_n_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nn_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nn_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nn_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nn_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_b_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_b_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_b_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_b_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bb_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bb_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bb_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bb_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_t_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_t_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_t_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_t_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_tt_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_tt_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_tt_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_tt_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cn_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cn_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cn_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cn_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cb_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cb_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cb_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_cb_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_ct_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_ct_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_ct_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_ct_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nb_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nb_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nb_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nb_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nt_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nt_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nt_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_nt_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bt_helmet, 1), new Object[]{"MMM","M M", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bt_chestplate, 1), new Object[]{"M M","MMM","MMM", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bt_leggings, 1), new Object[]{"MMM","M M","M M", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0)});
		GameRegistry.addRecipe(new ItemStack(ModTools.steel_bt_boots, 1), new Object[]{"M M","M M", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0)});

GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.rose_gold_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.rose_gold_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});	
		
GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(Items.iron_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(Items.iron_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(Items.iron_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(Items.iron_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.mod_iron_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(Items.iron_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});	
		
GameRegistry.addRecipe(new ItemStack(ModTools.copper_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.copper_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.copper_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.copper_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.copper_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.copper_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.copper_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.copper_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.copper_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.copper_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brassz_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brassz_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brassz_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brassz_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brassz_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.brass_z_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brasszz_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brasszz_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brasszz_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brasszz_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.brasszz_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.brass_zz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzet_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzet_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzet_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzet_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzet_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.bronze_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzett_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzett_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzett_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzett_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzett_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.bronze_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzetz_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzetz_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzetz_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzetz_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.bronzetz_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.bronze_tz_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelc_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelc_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelc_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelc_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelc_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_c_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcc_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcc_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcc_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcc_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcc_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_cc_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeln_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeln_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeln_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeln_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeln_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_n_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnn_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnn_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnn_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnn_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnn_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_nn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelb_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelb_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelb_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelb_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelb_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_b_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbb_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbb_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbb_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbb_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbb_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_bb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelt_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelt_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelt_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelt_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelt_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_t_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeltt_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeltt_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeltt_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeltt_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steeltt_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_tt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcn_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcn_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcn_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcn_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcn_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_cn_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcb_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcb_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcb_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcb_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelcb_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_cb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelct_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelct_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelct_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelct_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelct_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_ct_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnb_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnb_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnb_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnb_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnb_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_nb_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnt_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnt_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnt_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnt_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelnt_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_nt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbt_pick, 1), new Object[]{"MMM"," S ", " S ", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbt_axe, 1), new Object[]{"MM","SM", "S ", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbt_sword, 1), new Object[]{"M","M", "S", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbt_hoe, 1), new Object[]{"MM","S ", "S ", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});
GameRegistry.addRecipe(new ItemStack(ModTools.steelbt_shovel, 1), new Object[]{"M","S", "S", 'M', new ItemStack(ModItems.steel_bt_ingot, 1, 0), 'S', new ItemStack(Items.stick, 1, 0)});

}
}